### ISSUE TITLE
Include the Tiled tmx file

### ISSUE THREAD

**Issue by unstoppablecarl** [hexus/phaser-arcade-slopes#2]
Can you please add the tmx file to the demo repo?

**Comment by hexus** [comment]
https://github.com/hexus/phaser-arcade-slopes/blob/gh-pages/assets/maps/demo.json

The demo map is available on the gh-pages branch. I removed the .tmx in favour of the .json, as I much preferred editing the .json in Tiled directly rather than saving a .tmx and exporting a .json every time.

Hopefully this gives you what you need! The tilesheets are in that branch too.

Is there any reason you wanted the .tmx over the .json? As far as I'm aware they're functionally equivalent now when used with Tiled.

**Comment by unstoppablecarl** [comment]
I did not realize you could open the json file in tiled. Thanks!
