### ISSUE TITLE
Tiles disappear visually after resizing window

### ISSUE THREAD

**Issue by iCodeForBananas** [hexus/phaser-arcade-slopes#23]
https://streamable.com/dsmx
1. start browser smaller
2. resize your window by dragging it

Tiles disappear, seems like an initial window size is set and on resize it doesn't get updated.

**Comment by hexus** [comment]
I don't think this is an issue with the plugin. I've noticed you're reporting a lot of issues that might simply be issues with Phaser or how you're using it. Please try to verify that it's definitely an issue with the plugin before posting.

Can you confirm that this only happens when using the plugin?

**Comment by iCodeForBananas** [comment]
Sorry man I've have been working way to late at night.

I'll going to figure actually what's going on with this.
