### ISSUE TITLE
Overlap doesn't appear to account for empty space and overlaps them with ground 

### ISSUE THREAD

**Issue by iCodeForBananas** [hexus/phaser-arcade-slopes#7]
_UPDATE_

See down the conversation, the collide behavior looks like it's correct but you can't use overlap yet.
https://github.com/hexus/phaser-arcade-slopes/issues/7#issuecomment-229096109

_OLD_
The bullets hit the 50% slope and slide up.
![bullets5](https://cloud.githubusercontent.com/assets/8272012/16381760/deb2c480-3c32-11e6-88a1-3bf8133b77ca.gif)

The bullets go straight through and if you're shooting through a 10x10 the bullet will enter one side and collide with the opposite side.
![bullets5](https://cloud.githubusercontent.com/assets/8272012/16381803/0b8835a8-3c33-11e6-8751-a4272c6ba9ea.gif)

This is how I create 50 reusable bullets.

``` javascript
    this.bullets = this.game.add.group()
    this.bullets.createMultiple(50, 'bullet')
    this.bullets.setAll('checkWorldBounds', true)
    this.bullets.setAll('outOfBoundsKill', true)
    this.physics.arcade.enable(this.bullets)
    this.game.slopes.enable(this.bullets)
```

This is how I fire a bullet.

``` javascript
    let bullet = this.rootScope.bullets.getFirstDead()
    bullet.bulletId = Guid()
    bullet.damage = this.damage
    bullet.weaponId = this.meta.id
    bullet.height = this.bulletHeight
    bullet.width = this.bulletWidth
    bullet.alpha = 0
    bullet.body.gravity.y = -1800

    // Add a touch of tile padding for the collision detection
    bullet.body.tilePadding.x = 50
    bullet.body.tilePadding.y = 1

    bullet.reset(x, y)
    let pointerAngle = this.rootScope.game.physics.arcade.moveToPointer(bullet, this.bulletSpeed)
    bullet.rotation = pointerAngle

    setTimeout(() => {
        bullet.alpha = this.bulletAlpha !== undefined ? this.bulletAlpha : 1
    }, 40)
```

This is how I collide bullets with the slope ground.

``` javascript
    this.physics.arcade.collide(this.bullets, this.ground,  function(bullet) {
        bullet.kill()
    }, null, this)
```

Normally I use overlap though.

``` javascript
    this.physics.arcade.overlap(this.bullets, this.ground,  function(bullet) {
        bullet.kill()
    }, null, this)
```

but this has been happening.

![bullets5](https://cloud.githubusercontent.com/assets/8272012/16382030/fb4d6914-3c33-11e6-8c29-87128eeb1461.gif)

**Comment by hexus** [comment]
Interesting! Thanks for such a clear explanation.

If you have a way of setting up something like a codepen that I could use to diagnose this I'd be happy to look into it.

Something that jumps out at me immediately:

```
bullet.height = this.bulletHeight
bullet.width = this.bulletWidth
```

This is being set after enabling physics bodies for the particles of the emitter. Could it be that the body of each particle is larger than you expect? Perhaps you could find away to [draw debug output](http://phaser.io/examples/v2/debug/debug-physics) for the bodies of currently alive particles, just to get a better visual of what's going on. Might be helpful to do the same for the tilemap at the same time.

Unfortunately the plugin itself doesn't yet have its own debug output for all the polygons and vectors involved in the collision handling, but that is on the roadmap for 0.2.0 (#4).

**Comment by iCodeForBananas** [comment]
![bullets6](https://cloud.githubusercontent.com/assets/8272012/16421885/4f5ed0e2-3d0b-11e6-9f4e-8077ceb993a1.gif)

I was messing with the body width and height instead like you said.  I think the main issue is that I'm unable to use overlap instead of collide with the bullets.  I'll see if I can get a codepen together.

**Comment by iCodeForBananas** [comment]
Some of the particles in the example have a similar issue.
Change the collision on https://github.com/hexus/phaser-arcade-slopes/blob/gh-pages/src/ArcadeSlopesDemo.js#L300 to the below:

```
            // Collide the particles against the collision layer
            this.physics.arcade.overlap(this.emitter, this.ground, function(particle, ground) {
                particle.kill()
            }, null, this);
```

This should allow for the particles to come out of the player and when they overlap the ground be killed.
Instead they get killed instantly inside of the player object.

![bullets7](https://cloud.githubusercontent.com/assets/8272012/16422912/e1486f60-3d0e-11e6-96e3-dfea0b7adb85.gif)

**Comment by hexus** [comment]
Very interesting! I will absolutely investigate this at some point, thank you for highlighting it so well.

The plugin is probably not handling the `overlapOnly` flag correctly. :)

**Comment by michaeljcalkins** [comment]
![overlap test](https://cloud.githubusercontent.com/assets/8272012/16444210/d4f8fe9a-3d91-11e6-8cd0-862b59a12ac9.gif)

Unless I'm mistaken overlap is already in here somewhere.

**Comment by iCodeForBananas** [comment]
Ok so I don't really understand the consequences of my actions but I got it to kind of work now.

Go to this line:
https://github.com/hexus/phaser-arcade-slopes/blob/86c68867ca6ffce1c3a2cbe638571b199cc7c977/src/ArcadeSlopes/Overrides.js#L48

Replace the if statement with the following:

``` javascript
        if (! overlapOnly && collideCallback) {
            collideCallback.call(callbackContext, sprite, tile);
        }
```

![overlap test](https://cloud.githubusercontent.com/assets/8272012/16444452/dc189b80-3d92-11e6-9bf7-7c047a3873c1.gif)

**Comment by hexus** [comment]
Hmm, okay. That's interesting,  because that branch passes handling to Arcade Physics to handle normally, if the tile doesn't have a `tile.slope` property (i.e. it hasn't been converted by the plugin).

Except the callback should still be called in the case of an overlap. The code you've linked to is meant to mirror this, to an extent:

https://github.com/photonstorm/phaser/blob/master/src/physics/arcade/TilemapCollision.js#L63

Except I decided to break it down a little more to avoid code repetition. But perhaps the `return` statements I've used are causing issues down the line, or `separateTile()` is doing something that I'm not catering for properly.

Also, love that the Lenny face is in the example GIF, haha. What do you use for screen capture?

**Comment by iCodeForBananas** [comment]
LICEcap
http://www.cockos.com/licecap/

One of the most useful tools ever for showing people stuff!

**Comment by hexus** [comment]
I totally managed to reproduce the issue above, but even after completely disabling the plugin. This might be an issue with Phaser itself, and not the plugin.

**Comment by hexus** [comment]
Okay, so this _technically_ isn't a bug (but I think it is).

The callback is working as expected because the sprites **are indeed overlapping a tile**.

![phaser-overlap-bug-1](https://cloud.githubusercontent.com/assets/2626789/16504573/94df642c-3f10-11e6-94fc-59a0ce68e003.gif)

The problem, as highlighted in the GIF, is that these tiles shouldn't _collide_ and have an index of -1, but Phaser doesn't say anything about `overlap()` only checking tiles that collide. Whether this is correct is up for debate, but I feel like it isn't.

To work around this, you can add a **process callback**.

```
this.physics.arcade.overlap(this.emitter, this.ground, function (particle, tile) {
    particle.kill();
}, function (particle, tile) {
    return tile.collides;
}, this);
```

This will still check the overlap, but only for tiles that can collide. It should give the result you're after.

![phaser-overlap-bug-2-2](https://cloud.githubusercontent.com/assets/2626789/16504700/4790db50-3f11-11e6-8ecc-8472ca578fcf.gif)

Collision process callbacks in Phaser are a check that let you decide whether to actually continue with the overlap/collision based on the result of your own callback function. In this case, we simply check whether the current tile is meant to collide with anything.

Feel free to let me know if this resolves all of your issues. :smiley:

Also, _technically_, this means my plugin is incorrect, because it will bail out from `overlapOnly` collision checks if the tile doesn't collide, which is adverse to Phaser's above mentioned behaviour.

**Comment by hexus** [comment]
Oh, and [thanks for showing me LICEcap](https://github.com/hexus/phaser-arcade-slopes/commit/4b4ade7de7fe0527b8d1423a1c63e8c0732ae57a), it's fabulous! :sparkles:

**Comment by iCodeForBananas** [comment]
It totally worked!  I didn't get a chance to really test it a lot but immediately I was able to shoot again! :)

**Comment by iCodeForBananas** [comment]
Just a heads up for closure on this, it's works awesome!
I updated the sprite bodies and added the processCallback to other things needing overlap and it all works! :)

**Comment by hexus** [comment]
Awesome, thanks for letting me know. 

I did close this pre-emptively but I had a gut feeling that this was the cause of all your issues. I thought maybe something else would be causing the sliding/missing tiles, but assumed these were different attempts to get it working and ultimately you just wanted the correct overlap responses. :)

Glad it works so well! I look forward to seeing your project progress.
